name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- 1. LINT DOCKERFILE (On ignore les erreurs ici pour avancer) ---
      - name: 🐳 Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        continue-on-error: true
        with:
          dockerfile: Dockerfile

      # --- 2. SECRET SCANNING ---
      - name: 🔑 Secret Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- 3. SAST (Semgrep) ---
      - name: 🔍 SAST Scan (Semgrep)
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        with:
          generateSarif: "1"

      # --- 4. SCA (Trivy FS) ---
      - name: 📦 Dependency Scan (Trivy SCA)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # --- 5. IMAGE SCAN ---
      - name: 🖼️ Build and Scan Image
        run: |
          docker build -t flask-app:latest .
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasecurity/trivy image --exit-code 0 --severity CRITICAL flask-app:latest

      # --- 6. UPLOAD RESULTS (Indispensable) ---
      - name: 📊 Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: '.'
