name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- 1. LINT DOCKERFILE ---
      - name: 🐳 Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      # --- 2. SECRET SCANNING ---
      - name: 🔑 Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- 3. SAST (Semgrep) ---
      - name: 🔍 SAST Scan (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
          generateSarif: "1"

      # --- 4. SCA (Trivy FS) ---
      - name: 📦 Dependency Scan (Trivy SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Fait échouer le job si des failles sont trouvées

      # --- 5. IMAGE SCAN ---
      - name: 🖼️ Build Image
        run: docker build -t flask-app:latest .

      - name: 🛡️ Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-app:latest'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL'
          exit-code: '1' # Fait échouer le job si l'image est trop vulnérable

      # --- 6. UPLOAD RESULTS (Toujours exécuté grâce au if: always) ---
      - name: 📊 Upload Semgrep Results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'semgrep.sarif'
          category: 'semgrep'

      - name: 📊 Upload Trivy FS Results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-fs'

      - name: 📊 Upload Trivy Image Results
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'trivy-image'
